# games.py

from utils import *
from data import *
from player_stats import update_mode_stats

def play_letters(stats): ...
def play_words(stats): ...
def play_numbers(stats): ...
def play_combinations(stats): ...
def play_sentences(stats): ...
def play_fill_blanks(stats): ...