# utils.py

import unicodedata
import sys

def color(text, code): ...
def green(text): ...
def red(text): ...
def yellow(text): ...
def blue(text): ...
def magenta(text): ...
def bold(text): ...
def cyan(text): ...
def congrats_streak(streak): ...
def strip_greek_accents(s):
    return ''.join(
        c for c in unicodedata.normalize('NFD', s) if not unicodedata.combining(c)
    )